---
###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  tasks:
  - import_role: 
      name: create-cluster
    tags: always
  environment:
    KOPS_STATE_STORE: "{{ state_store }}"
