---

- name: Fetch current cluster config
  shell: 'kops get cluster --name {{ cluster_name }} -o yaml > /tmp/{{ cluster_name }}-cluster-conf.yaml'
  changed_when: false

- name: adding cluster config
  blockinfile:
    path: "/tmp/{{ cluster_name }}-cluster-conf.yaml"
    insertafter: "spec:"
    block: "{{ lookup('file', '{{ playbook_dir }}/config_addons.yml') | indent(width=2, indentfirst=True) }}"
  notify: 'Push cluster config'

- name: Configure Classic LB to be NLB for masters
  lineinfile:
    path: /tmp/{{ cluster_name }}-cluster-conf.yaml
    regexp: '^(\s+)class:'
    line: '\1class: Network'
    backrefs: yes
  notify: 'Push cluster config'

- name: Run handlers
  meta: flush_handlers
