---

- name: Fetch current instance groups config
  shell: 'kops get instancegroups --name {{ cluster_name }} -o yaml > /tmp/{{ cluster_name }}-ig-conf.yaml'
  changed_when: false

- name: Configure node min instances
  lineinfile:
    path: /tmp/{{ cluster_name }}-ig-conf.yaml
    regexp: '^(\s+)minSize:'
    line: '\1minSize: {{ node_autoscaler_min }}'
    backrefs: yes
  notify: 'Push cluster config'

- name:	Configure node max instances
  lineinfile:
    path: /tmp/{{ cluster_name }}-ig-conf.yaml
    regexp: '^(\s+)maxSize:'
    line: '\1maxSize: {{ node_autoscaler_max }}'
    backrefs: yes
  notify: 'Push cluster config'

- name: Run handlers
  meta: flush_handlers
